project_id = "byjwgtztyafzgxxzvnge"

[api]
enabled = true
port = 54321
schemas = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"